FROM tomcat
RUN apt update
RUN apt install maven -y
RUN apt install git -y
RUN mkdir project
RUN cd /project
RUN git clone https://github.com/boxfuse/boxfuse-sample-java-war-hello.git
RUN cd /project/boxfuse-sample-java-war-hello/
RUN mvn package
RUN cp /project/boxfuse-sample-java-war-hello/target/hello-1.0.war /usr/local/tomcat/webapps/
EXPOSE 8080
CMD ["tomcat"]
